// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import DisplayImgOnCreateController from "./display_img_on_create_controller.js"
application.register("display-img-on-create", DisplayImgOnCreateController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import MessageController from "./message_controller.js"
application.register("message", MessageController)

import RangeEffectController from "./range_effect_controller.js"
application.register("range-effect", RangeEffectController)

import ShowDescriptionController from "./show_description_controller.js"
application.register("show-description", ShowDescriptionController)

import SwipeImgController from "./swipe_img_controller.js"
application.register("swipe-img", SwipeImgController)

import ToggleInputSearchController from "./toggle_input_search_controller.js"
application.register("toggle-input-search", ToggleInputSearchController)

import ToggleProductController from "./toggle_product_controller.js"
application.register("toggle-product", ToggleProductController)
