---
:concurrency: 3
:queues:
  - jokou_default
  - jokou_mailers

:scheduler:
  :schedule:
    banner:
      # cron: '0 0 * * * * Africa/Abidjan'   
      class: BannerJob
      every: '24h'
      enable: true
    
    bid_active:
      every: '3s'
      class: SetBidStateJob
      enable: true